node
{
    def mvnHome = tool name: 'maven3', type: 'maven'
    
   stage('=============================Preparation====================================') { 
     
      git 'https://github.com/vijaycgovind/india.git'
      
   }
   
   stage('Clean') {
      // Run the maven clean
    // def mp = tool name: '/Users/vijaygovind/apache-maven-3.5.4', type: 'maven'
   
      
      
      sh "${mvnHome}/bin/mvn clean"
   
   }
    stage ('---------------------Test---------------------------------')
    {
         sh "${mvnHome}/bin/mvn test"
   }
   
   stage('------------------------PACKAGE-------------------------') 
   {
    echo $PWD
    sh "${mvnHome}/bin/mvn package"
   }
}
