node
{
    def mvnHome = tool name: 'maven3', type: 'maven'
    
   stage('=============================Preparation====================================') { 
     
      git 'https://github.com/vijaycgovind/india.git'
      
   }
   
   
   stage('------------------------INSTALL-------------------------') 
   {
 
    sh "${mvnHome}/bin/mvn -f india/pom.xml clean install"
 
   }
}
