node
{
    def mvnHome = tool name: 'maven3', type: 'maven'
    
   stage('=============================Preparation====================================') { 
     
      git 'https://github.com/vijaycgovind/india.git'
      
   }
   
   
   stage('------------------------INSTALL-------------------------') 
   {
    //echo $pwd
    path=$PWD
    echo $path
    sh "${mvnHome}/bin/mvn clean install"
   }
}
